# Shamelessly stolen from: https://github.com/nvim-treesitter/nvim-treesitter/
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "None"
